[project]
name = "expense-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard,standrad]>=0.115.11",
    "sqlalchemy>=2.0.38",
    "sqlmodel>=0.0.24",
]
